spring:
  datasource:
    url: jdbc:mysql://192.168.1.4:3306/demo
    
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL8Dialect
    
server:
  port: 5505    
         
